services:

  backend:
    build: ./backend
    ports:
      - "5000:8080"
    volumes:
    - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:80"
    depends_on:
      - backend
